// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OnAfterMerge is an autogenerated mock type for the OnAfterMerge type
type OnAfterMerge struct {
	mock.Mock
}

// OnAfterMerge provides a mock function with given fields: targetpath, sourcePath
func (_m *OnAfterMerge) OnAfterMerge(targetpath string, sourcePath string) error {
	ret := _m.Called(targetpath, sourcePath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(targetpath, sourcePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
