// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OnBeforeMerge is an autogenerated mock type for the OnBeforeMerge type
type OnBeforeMerge struct {
	mock.Mock
}

// OnBeforeMerge provides a mock function with given fields: targetPath, sourcePath
func (_m *OnBeforeMerge) OnBeforeMerge(targetPath string, sourcePath string) error {
	ret := _m.Called(targetPath, sourcePath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(targetPath, sourcePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
